### ISSUE TITLE
Replace file_get_contents with cURL or guzzlehttp/guzzle package

### ISSUE THREAD

**Issue by peter279k** [three-cos/loripsum#1]
As title, it seems that this package uses the `file_get_contents` to make HTTP requests. However, this above approach is not secure and it will not be convenient for developers to make HTTP requests, too.

In my opinion, I think it can use cURL or guzzlehttp/guzzle to prevent above issue.

Here is the [reference](https://www.vaadata.com/blog/understanding-web-vulnerability-server-side-request-forgery-1/) about this security issue.

**Comment by three-cos** [comment]
Thank you for mentioning this issue, I'll take a look to fix this.
I used `file_get_contents` just to make it super-simple.

**Comment by three-cos** [comment]
Switched `file_get_contents` to `guzzlehttp/guzzle` in https://github.com/three-cos/loripsum/commit/9cccb5992253019bb679828a2901f3333421fd56
